version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 2.6.5
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
    ports:
      - 4000:3000
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    depends_on:
      - chrome
    environment:
      - "SELENIUM_HUB_URL=http://chrome:4444/wd/hub"
      - "TEST_APP_HOST=app"
      - "TEST_APP_PORT=3001"
  chrome:
    image: selenium/standalone-chrome:3.141.59-iron
    ports:
      - "4444:4444"
  db:
    image: "mysql:5.7.21"
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  mysql-data:
