version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 2.6
        # [Choice] Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    
    # Uncomment the next line to use a non-root user for all processes.
    user: vscode
    depends_on:
      - chrome
    environment:
      - "SELENIUM_HUB_URL=http://chrome:4444/wd/hub"
      - "TEST_APP_HOST=app"
      - "TEST_APP_PORT=3001"
  chrome:
    image: selenium/standalone-chrome:3.141.59-iron
    ports:
      - "4444:4444"
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5000:5432
    environment:
      POSTGRES_USER: vscode
      POSTGRES_DB: bootcamp_development
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres-data:
